version: "3.5"
services:
  database_master:
    image: mysql:8.0.30
    container_name: "database_master"
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysqldata_master:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=PaletteSecret123
      - MYSQL_USER=palette
      - MYSQL_DATABASE=palette
      - MYSQL_PASSWORD=PaletteSecret123
    networks:
      - mynetwork
networks:
  mynetwork:
volumes:
  mysqldata_master:
