spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect

---

spring:
  profiles:
    group:
      "local": "localdb, common"
      "dev": "devdb, common"
      "prod": "proddb, common"

---

spring:
  config:
    activate:
      on-profile: "localdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/palette?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: localpalette
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: info

---

spring:
  config:
    activate:
      on-profile: "devdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:9090/devpalette?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: testpass
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: info

---

spring:
  config:
    activate:
      on-profile: "proddb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:7000/prodpalette?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: testpass
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: info

---

spring: #공통환경
  config:
    activate:
      on-profile: "common"
  sql:
    init:
      mode: always
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
#server:
#  tomcat:
#    connection-timeout: 5000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /temp/**