spring:
  profiles:
    group:
      "local": "localdb, common"
      "dev": "devdb, common"
      "prod": "proddb, common"
    include: "jwt, aws"
    active: dev
---

spring: #공통환경
  config:
    activate:
      on-profile: "common"
  sql:
    init:
      mode: always
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  main:
    allow-bean-definition-overriding: true

---


springdoc:
  swagger-ui:
    #    path: /swagger-ui.html
    #    path: /test-swagger

    groups-order: asc
    operationsSorter: method
    #    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---

#server:
#  servlet:
#    context-path: /api